apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyGateway
gateway:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
provider:
  type: Custom
  custom:
    resource:
      type: File
      file:
        paths: ["/etc/envoy-gateway/config.yaml"]
    infrastructure:
      type: Host
      host:
        name: envoy-gateway
        namespace: envoy-gateway-system
logging:
  level:
    default: debug
extensionApis:
  enableBackend: true
  enableOAuth: true