version: '3.7'
services:
  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    container_name: kong-postgres
    restart: on-failure
    networks:
      - kong-net
    volumes:
      - kong_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: Matiisetso2013
      POSTGRES_DB: kong
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:latest
    command: kong migrations bootstrap
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: Matiisetso2013
    depends_on:
      - kong-database

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:latest
    restart: on-failure
    container_name: kong
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: Matiisetso2013
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-database
    volumes:
      - ./kong/go-pluginserver/go-pluginserver:/usr/local/bin/go-pluginserver
      - ./kong/plugins:/usr/local/kong/plugins/
      - ./kong/go-plugins:/usr/local/kong/go_plugins/
      - ./kong/kong.conf:/etc/kong/kong.conf
      - ./kong/tls:/etc/pki/tls
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"

  #######################################
  # Konga database prepare
  #######################################
  # konga-prepare:
  #   image: pantsel/konga:latest
  #   command: "-c prepare -a postgres -u postgresql://kong:Matiisetso2013@kong-database:5432/konga"
  #   networks:
  #     - kong-net
  #   restart: on-failure
  #   depends_on:
  #     - kong-database

  #######################################
  # Konga: Kong GUI
  #######################################
  # konga:
  #   image: pantsel/konga:latest
  #   container_name: konga
  #   restart: always
  #   networks:
  #     - kong-net
  #   environment:
  #     DB_ADAPTER: postgres
  #     DB_URI: postgresql://kong:Matiisetso2013@kong-database:5432/konga
  #     NODE_ENV: production
  #   depends_on:
  #     - kong-database
  #   ports:
  #     - "1337:1337"